[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r scripts/scripts/requirements.txt"]

[start]
cmd = "/opt/venv/bin/python scripts/scrapers/wolf_hunter.py"