[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "gcc", "nodejs_20", "npm"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "/opt/venv/bin/python3 -u $EXEC_SCRIPT"